### ISSUE TITLE
Datepicker/Calendar messenger4j

### ISSUE THREAD

**Issue by riri93** [messenger4j/messenger4j-spring-boot-quickstart-template#20]
Is there a date picker or calendar type in messenger4j API?

**Comment by maxgrabenhorst** [comment]
Hi, no there is not such a feature in messenger4j since FB does not provide this capabilities so far.
You can take a look at the latest messenger4j version which supports built-in NLP. Using this feature you can extract date information from text messages. Another alternative would be to use a Webview which could provide a date-picker.
